stages:
  - build
  - production

job_build:
  stage: build
  tags:
    - windows
  script:
    - echo Hello, %USERNAME%!
  only:
    - tags

job_production:
  stage: production
  tags:
    - windows
  script:
    - echo Hello, %USERNAME%!
  only:
    - tags
  when: on_success